apiVersion: v1
kind: Pod
metadata:
  name: ${APP_NAME}-kaniko-builder
  namespace: default
spec:
  serviceAccountName: kaniko-builder
  restartPolicy: Never
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args:
    - "--dockerfile=${DOCKERFILE_PATH}"
    - "--context=s3://${S3_BUCKET}/${APP_NAME}.tar.gz"
    - "--destination=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APP_NAME}:${IMAGE_TAG}"
    - "--cache=${ENABLE_CACHE}"
    - "--cache-repo=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/kaniko-cache"
    - "--cleanup"
    env:
    - name: AWS_SDK_LOAD_CONFIG
      value: "true"
    - name: AWS_REGION
      value: "${AWS_REGION}"
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"
    volumeMounts:
    - name: aws-iam-token
      mountPath: /var/run/secrets/eks.amazonaws.com/serviceaccount
      readOnly: true
  volumes:
  - name: aws-iam-token
    projected:
      sources:
      - serviceAccountToken:
          path: token
          expirationSeconds: 86400
